spring:
  application:
    name: spring-rest-api
  
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: qblstklk50n0ijjcbp1t6vhqov7q181k.apps.googleusercontent.com
            client-secret: _PtMRw4JF5Pp4obDjXy
            redirect-uri: http://localhost:3000/auth/callback/google
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


# cors 추가 설정 : swagger 을 위해 추가 : do-dev.yml APP_CORS_ALLOWED_ORIGINS 도 같이 추가 필요 
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080,http://134.185.106.168,http://134.185.106.168:8080
  file:
    upload-dir: /uploads/
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx
    max-size: 50MB

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    persist-authorization: true
    groups-order: ASC

# 기본 서버 설정
server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: true

jasypt:
  encryptor:
    password: "sospringapp"
    algorithm: "PBEWithMD5AndDES"
    key-obtention-iterations: "1000"
    pool-size: "1"
    provider-name: "SunJCE"
    salt-generator-classname: "org.jasypt.salt.RandomSaltGenerator"
    iv-generator-classname: "org.jasypt.iv.NoIvGenerator"
    string-output-type: "base64"

mybatis:
  configuration:
    map-underscore-to-camel-case: true
